### ISSUE TITLE
Token skips movement animation between waypoints when entering/exiting auras

### ISSUE THREAD

**Issue by Cuingamehtar** [7H3LaughingMan/pf2e-ruler#1]
Seems like token update caused by adding effects from auras results in token skipping its movement animation to the next waypoint.

Example:
1) Have actor token A with friendly aura.
2) Move token B (allied with A) by placing a waypoint inside the aura range and the next one - outside.
Token B will skip animation from the inside waypoint to the outside. This works both ways.
But when zig-zagging, not every animation is skipped.

**Comment by 7H3LaughingMan** [comment]
I was able to re-produce it, but the for me it only happened if I had a player token moving diagonally up and down across another player with the bless aura. I will take a look at it; however, at the moment nothing about the movement animation is changed so it's the base animation you get when using the ruler without the module. Was able to re-produce it without any modules installed.

**Comment by Cuingamehtar** [comment]
Ah, I didn't check if it was core behavior.
I haven't switched my game to v12 yet but I don't remember this happening for me with Drag Ruler in v11.
