### ISSUE TITLE
Unresolved Dependancies

### ISSUE THREAD

**Issue by perrinaz** [7H3LaughingMan/pf2e-ruler#12]
The module does not specify a dependency on libwrapper and does not trigger the system to ask the user if they wish it installed.

**Comment by 7H3LaughingMan** [comment]
I am not sure what you are looking at, but it does specify libwrapper as a requirement.

https://github.com/7H3LaughingMan/pf2e-ruler/blob/9969d81d590fe423d96f019c71d9694603b38d92/module.json#L43
