### ISSUE TITLE
On Google Chrome, dragging token as a GM does not show distance.

### ISSUE THREAD

**Issue by tcordeki** [7H3LaughingMan/pf2e-ruler#16]
When dragging a token around as a GM, I do not see the distance dragged. When one of my players drags their token, I am able to see the distance they are moving their token, as intended. Deactivating all other modules does not fix this issue.

I am using The Forge for hosting, and am on Foundry version 12 Stable and pf2e v6.1.0. This issue does not occur when using Firefox.

**Comment by farling42** [comment]
Is your "Show GM Ruler" module setting to "none"?

**Comment by tcordeki** [comment]
It is set to "Show Friendly", though that shouldn't stop the GM from seeing their own ruler, it only stops the players from seeing the ruler based on the setting (so they can't see enemy rulers while the GM is moving them around).
