### ISSUE TITLE
Add pathfinding effect

### ISSUE THREAD

**Issue by Lioheart** [7H3LaughingMan/pf2e-ruler#5]
Is it possible to add a pathfinding option? My players often get stuck in walls and this option would be very useful for them.

**Comment by insquared** [comment]
Yes, this is a  heavily used feature in our games, please add this feature.

**Comment by apoapostolov** [comment]
Came to ask the same question. I rely on pathfinding for hard angles in dungeons. I switched to Elevation Ruler for that reason, and it got a very good PF2 support. AFAIK if this mod shares code with Drag Ruler, it may be easy to add support for routinglib which Drag Ruler uses.
