### ISSUE TITLE
[Bug] Moving tokens smaller than 1 grid size bugs out weirdly

### ISSUE THREAD

**Issue by ChasarooniZ** [7H3LaughingMan/pf2e-ruler#7]
It doesn't allow you to move a creature of size 0.5 x 0.5 grid units inside of the grid. Mostly an issue for familiars

**Comment by mechamaya** [comment]
Also any tiny creatures have this issue. They are stuck to whatever corner they were created at within squares.

**Comment by Duncan-Henry** [comment]
It seems like it might also have to do with the token's initial position relative to a square. If you shift+click a token somewhere else, subsequent movements will be in the same position relative to their destination.

**Comment by ChrisEurolog** [comment]
I am getting a similar issue on 6.5.1 for large creatures that centre themselved in the middle of a square rather that at the central intersection of the 4 squares

**Comment by ChrisEurolog** [comment]
Great mod btw!

**Comment by Pfodge** [comment]
Just to add to and clarify what everyone in this thread is saying: here's a video with creatures of size Tiny, Large, and Gargantuan on the top row, and creatures of size Small, Medium, and Huge on the bottom row. 


https://github.com/7H3LaughingMan/pf2e-ruler/assets/174600051/05940cb9-d21f-4023-bac7-2a108ec7c625



Anything of a size not centred in the middle of a grid square breaks unfortunately. This video was taken in a world with no other modules active

**Comment by ChasarooniZ** [comment]
Adding Comment, that there is fix. However we can no longer place tiny creatures on the edge of grids (which i assume is intended behavior for the system)
